require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '11.0'

target 'ReactNativeIDnowSample' do 
  # START
  # Without this we cannot install Flipper along with ID Now v5.3.0
  $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
    'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
    'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
    'CocoaLibEvent', 'openssl-ios-bitcode', 'boost-for-react-native', 'RCT-Folly', 'React-jsi', 'React-cxxreact',
    'React-jsiexecutor', 'React-Core', 'React-RCTText', 'ReactCommon', 'RCTTypeSafety', 'FBReactNativeSpec',
    'React-RCTSettings', 'React-RCTLinking', 'React-RCTVibration', 'React-RCTAnimation', 'React-RCTNetwork',
    'React-RCTImage','React-RCTBlob', 'React-CoreModules']

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      
      if pod.respond_to?(:product_type) and pod.product_type == "com.apple.product-type.bundle"
        pod.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
      
      
    
      pod.build_settings['ARCHS'] = '${ARCHS_STANDARD_64_BIT}'
        if $static_framework.include?(pod.name)
          def pod.build_type;
            Pod::BuildType.static_library
          end
        end
      end
  end
  # END

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  
  use_frameworks!
  pod 'IDnowSDK', '6.1.4'

  target 'ReactNativeIDnowSampleTests' do
     inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!({ 'Flipper' => '0.87.0' })  

  post_install do |installer|
    react_native_post_install(installer)
  end
end
